#! /bin/sh

DST=apps/WebAlbums-ea/

for PROJ in iDAO Plugins iService Commons
do
  cp ../WebAlbums-$PROJ/dist/WebAlbums-$PROJ.jar $DST/lib/WebAlbums-$PROJ.jar -v
done
for PROJ in DAO-JPABeans Service-Beans 
do
  cp ../WebAlbums-$PROJ/dist/WebAlbums-$PROJ.jar $DST/WebAlbums-$PROJ.jar -v
done
for PROJ in Servlet FS
do
cp ../WebAlbums-$PROJ/dist/WebAlbums-$PROJ.war $DST/WebAlbums-$PROJ.war -v
done
cp ../WebAlbums-FS/JnetFS_Java/dist/JnetFS_Java.jar apps/WebAlbums-ea/lib
