#! /bin/sh
TOMEE_HOME=$(dirname $0)
DEFAULT_CONF_PATH_FILE=$TOMEE_HOME/conf/config.path

while [[ $# > 0 ]]
do
  key=$1
  case $key in
    -v|--verbose)
    verbose=1
    ;;
    -cp|--copy)
    cd $TOMEE_HOME
    sh ./to_copy
    cd -
    ;;
    -cfg|--config-file)
    shift
    CONFIG_PATH=$1
    ;;
    -h|--help)
    echo "no help yet, read the script file!"
    exit
    ;;
    *)
    # unknown option
    ;;
  esac
  shift    
done

if [ -z $CONFIG_PATH ]
then
    CONFIG_PATH=$(cat $DEFAULT_CONF_PATH_FILE)
fi

if [ -z $verbose ]
then
    LOGGING="-Djava.util.logging.config.file=$TOMEE_HOME/conf/logging.properties \
             -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager"
fi

CP=\
$TOMEE_HOME/bin/bootstrap.jar:\
$TOMEE_HOME/bin/tomcat-juli.jar:\
$TOMEE_HOME/lib/jandex-1.2.0.Final.jar

java -Djava.security.auth.login.config=$TOMEE_HOME/conf/login.config           \
     -Dopenejb.authentication.realmName=PropertiesLogin                        \
      $LOGGING                                                                 \
     -Djava.endorsed.dirs=$TOMEE_HOME/endorsed                                 \
     -classpath $CP                                                            \
     -Dcatalina.base=$TOMEE_HOME                                               \
     -Dcatalina.home=$TOMEE_HOME                                               \
     -Dconfig.path=$CONFIG_PATH                                                \
org.apache.catalina.startup.Bootstrap start 
