/* DO NOT EDIT THIS FILE - it is machine generated */
#define FUSE_USE_VERSION 26
#define JNETFS_JVM_VERSION JNI_VERSION_1_6

#include <jni.h>
#include <jni_md.h>
/* Header for class com_jnetfs_client_JnetFS */

#ifndef _Included_com_jnetfs_client_JnetFS
#define _Included_com_jnetfs_client_JnetFS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnetfs_core_JnetFS
 * Method:    mount
 * Signature: ([Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_jnetfs_core_JnetFS_mount
  (JNIEnv *, jobject, jobjectArray, jboolean);

/*
 * Class:     com_jnetfs_core_JnetFS
 * Method:    umount
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jnetfs_core_JnetFS_umount
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
