package entity.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Tag table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Tag"
 */
public abstract class BaseTag  implements Serializable {

  public static String PROP_ID = "ID";
  public static String PROP_TAG_TYPE = "TagType";
  public static String PROP_NOM = "Nom";
  
  
  private int hashCode = Integer.MIN_VALUE;
  
  // primary key
  private java.lang.Integer _iD;
  
  // fields
  private java.lang.String _nom;
  private java.lang.Integer _tagType;
  private java.lang.Integer _photo  ;


  // constructors
  public BaseTag () {
    initialize();
  }

  /**
   * Constructor for primary key
   */
  public BaseTag (java.lang.Integer _iD) {
    this.setID(_iD);
    initialize();
  }

  protected void initialize () {}



  /**
   * Return the unique identifier of this class
   * @hibernate.id
   *  generator-class="increment"
   *  column="ID"
   */
  public java.lang.Integer getID () {
    return _iD;
  }

  /**
   * Set the unique identifier of this class
   * @param _iD the new ID
   */
  public void setID (java.lang.Integer _iD) {
    this._iD = _iD;
    this.hashCode = Integer.MIN_VALUE;
  }

  
  /**
   * Return the value associated with the column: Nom
   */
  public java.lang.String getNom () {
    return _nom;
  }
  
  /**
   * Set the value related to the column: Nom
   * @param _nom the Nom value
   */
  public void setNom (java.lang.String _nom) {
    this._nom = _nom;
  }
  
  /**
   * Return the value associated with the column: TagType
   */
  public java.lang.Integer getTagType () {
    return _tagType;
  }
  
  /**
   * Set the value related to the column: TagType
   * @param _tagType the TagType value
   */
  public void setTagType (java.lang.Integer _tagType) {
    this._tagType = _tagType;
  }
  

  public boolean equals (Object obj) {
    if (null == obj) return false;
    if (!(obj instanceof entity.base.BaseTag)) return false;
    else {
      entity.base.BaseTag mObj = (entity.base.BaseTag) obj;
      if (null == this.getID() || null == mObj.getID()) return false;
      else return (this.getID().equals(mObj.getID()));
    }
  }
  
  
  public int hashCode () {
    if (Integer.MIN_VALUE == this.hashCode) {
      if (null == this.getID()) return super.hashCode();
      else {
	String hashStr = this.getClass().getName() + ":" + this.getID().hashCode();
	this.hashCode = hashStr.hashCode();
      }
    }
    return this.hashCode;
  }
  
  
  public String toString () {
    return super.toString();
  }
}