package Entity.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TagAlbum table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TagAlbum"
 */
public abstract class BaseTagAlbum  implements Serializable {

	public static String PROP_ALBUM_I_D = "AlbumID";
	public static String PROP_ID = "ID";
	public static String PROP_TAG_I_D = "TagID";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _iD;

	// fields
	private java.lang.Integer _albumID;
	private java.lang.Integer _tagID;


	// constructors
	public BaseTagAlbum () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTagAlbum (java.lang.Integer _iD) {
		this.setID(_iD);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="ID"
     */
	public java.lang.Integer getID () {
		return _iD;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _iD the new ID
	 */
	public void setID (java.lang.Integer _iD) {
		this._iD = _iD;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AlbumID
	 */
	public java.lang.Integer getAlbumID () {
		return _albumID;
	}

	/**
	 * Set the value related to the column: AlbumID
	 * @param _albumID the AlbumID value
	 */
	public void setAlbumID (java.lang.Integer _albumID) {
		this._albumID = _albumID;
	}


	/**
	 * Return the value associated with the column: TagID
	 */
	public java.lang.Integer getTagID () {
		return _tagID;
	}

	/**
	 * Set the value related to the column: TagID
	 * @param _tagID the TagID value
	 */
	public void setTagID (java.lang.Integer _tagID) {
		this._tagID = _tagID;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof Entity.base.BaseTagAlbum)) return false;
		else {
			Entity.base.BaseTagAlbum mObj = (Entity.base.BaseTagAlbum) obj;
			if (null == this.getID() || null == mObj.getID()) return false;
			else return (this.getID().equals(mObj.getID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}