package entity.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Album table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Album"
 */
public abstract class BaseAlbum  implements Serializable {

	public static String PROP_ID = "ID";
	public static String PROP_DATE = "Date";
	public static String PROP_SOURCE = "Source";
	public static String PROP_THEME = "Theme";
	public static String PROP_PICTURE = "Picture";
	public static String PROP_NOM = "Nom";
	public static String PROP_DESCRIPTION = "Description";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _iD;

	// fields
	private java.lang.String _nom;
	private java.lang.String _description;
	private java.lang.Integer _theme;
	private java.util.Date _date;
	private java.lang.String _source;
	private java.lang.String _picture;


	// constructors
	public BaseAlbum () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAlbum (java.lang.Integer _iD) {
		this.setID(_iD);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="ID"
     */
	public java.lang.Integer getID () {
		return _iD;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _iD the new ID
	 */
	public void setID (java.lang.Integer _iD) {
		this._iD = _iD;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: Description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: Description
	 * @param _description the Description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: Theme
	 */
	public java.lang.Integer getTheme () {
		return _theme;
	}

	/**
	 * Set the value related to the column: Theme
	 * @param _theme the Theme value
	 */
	public void setTheme (java.lang.Integer _theme) {
		this._theme = _theme;
	}


	/**
	 * Return the value associated with the column: Date
	 */
	public java.util.Date getDate () {
		return _date;
	}

	/**
	 * Set the value related to the column: Date
	 * @param _date the Date value
	 */
	public void setDate (java.util.Date _date) {
		this._date = _date;
	}


	/**
	 * Return the value associated with the column: Source
	 */
	public java.lang.String getSource () {
		return _source;
	}

	/**
	 * Set the value related to the column: Source
	 * @param _source the Source value
	 */
	public void setSource (java.lang.String _source) {
		this._source = _source;
	}


	/**
	 * Return the value associated with the column: Picture
	 */
	public java.lang.String getPicture () {
		return _picture;
	}

	/**
	 * Set the value related to the column: Picture
	 * @param _picture the Picture value
	 */
	public void setPicture (java.lang.String _picture) {
		this._picture = _picture;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof entity.base.BaseAlbum)) return false;
		else {
			entity.base.BaseAlbum mObj = (entity.base.BaseAlbum) obj;
			if (null == this.getID() || null == mObj.getID()) return false;
			else return (this.getID().equals(mObj.getID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}