package Entity.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the TagPhoto table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="TagPhoto"
 */
public abstract class BaseTagPhoto  implements Serializable {

	public static String PROP_ID = "ID";
	public static String PROP_TAG_I_D = "TagID";
	public static String PROP_PHOTO_I_D = "PhotoID";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _iD;

	// fields
	private java.lang.Integer _photoID;
	private java.lang.Integer _tagID;


	// constructors
	public BaseTagPhoto () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseTagPhoto (java.lang.Integer _iD) {
		this.setID(_iD);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="ID"
     */
	public java.lang.Integer getID () {
		return _iD;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _iD the new ID
	 */
	public void setID (java.lang.Integer _iD) {
		this._iD = _iD;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: PhotoID
	 */
	public java.lang.Integer getPhotoID () {
		return _photoID;
	}

	/**
	 * Set the value related to the column: PhotoID
	 * @param _photoID the PhotoID value
	 */
	public void setPhotoID (java.lang.Integer _photoID) {
		this._photoID = _photoID;
	}


	/**
	 * Return the value associated with the column: TagID
	 */
	public java.lang.Integer getTagID () {
		return _tagID;
	}

	/**
	 * Set the value related to the column: TagID
	 * @param _tagID the TagID value
	 */
	public void setTagID (java.lang.Integer _tagID) {
		this._tagID = _tagID;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof Entity.base.BaseTagPhoto)) return false;
		else {
			Entity.base.BaseTagPhoto mObj = (Entity.base.BaseTagPhoto) obj;
			if (null == this.getID() || null == mObj.getID()) return false;
			else return (this.getID().equals(mObj.getID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}