package entity.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Utilisateur table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Utilisateur"
 */
public abstract class BaseUtilisateur  implements Serializable {

	public static String PROP_ID = "ID";
	public static String PROP_PASSWORD = "Password";
	public static String PROP_NOM = "Nom";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _iD;

	// fields
	private java.lang.String _nom;
	private java.lang.String _password;
	
	// constructors
	public BaseUtilisateur () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUtilisateur (java.lang.Integer _iD) {
		this.setID(_iD);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="ID"
     */
	public java.lang.Integer getID () {
		return _iD;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _iD the new ID
	 */
	public void setID (java.lang.Integer _iD) {
		this._iD = _iD;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: Password
	 */
	public java.lang.String getPassword () {
		return _password;
	}

	/**
	 * Set the value related to the column: Password
	 * @param _password the Password value
	 */
	public void setPassword (java.lang.String _password) {
		this._password = _password;
	}

	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof entity.base.BaseUtilisateur)) return false;
		else {
			entity.base.BaseUtilisateur mObj = (entity.base.BaseUtilisateur) obj;
			if (null == this.getID() || null == mObj.getID()) return false;
			else return (this.getID().equals(mObj.getID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}