package Entity.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Photo table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Photo"
 */
public abstract class BasePhoto  implements Serializable {

	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_ID = "ID";
	public static String PROP_ALBUM = "Album";
	public static String PROP_PATH = "Path";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _iD;

	// fields
	private java.lang.String _description;
	private java.lang.Integer _album;
	private java.lang.String _path;


	// constructors
	public BasePhoto () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePhoto (java.lang.Integer _iD) {
		this.setID(_iD);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="ID"
     */
	public java.lang.Integer getID () {
		return _iD;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _iD the new ID
	 */
	public void setID (java.lang.Integer _iD) {
		this._iD = _iD;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: Description
	 * @param _description the Description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: Album
	 */
	public java.lang.Integer getAlbum () {
		return _album;
	}

	/**
	 * Set the value related to the column: Album
	 * @param _album the Album value
	 */
	public void setAlbum (java.lang.Integer _album) {
		this._album = _album;
	}


	/**
	 * Return the value associated with the column: Path
	 */
	public java.lang.String getPath () {
		return _path;
	}

	/**
	 * Set the value related to the column: Path
	 * @param _path the Path value
	 */
	public void setPath (java.lang.String _path) {
		this._path = _path;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof Entity.base.BasePhoto)) return false;
		else {
			Entity.base.BasePhoto mObj = (Entity.base.BasePhoto) obj;
			if (null == this.getID() || null == mObj.getID()) return false;
			else return (this.getID().equals(mObj.getID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}