package entity.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the Geolocalisation table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="Geolocalisation"
 */
public abstract class BaseGeolocalisation  implements Serializable {

	public static String PROP_LAT = "Lat";
	public static String PROP_LONG = "Long";
	public static String PROP_TAG = "Tag";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _tag;

	// fields
	private java.lang.String _lat;
	private java.lang.String _long;


	// constructors
	public BaseGeolocalisation () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseGeolocalisation (java.lang.Integer _tag) {
		this.setTag(_tag);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="increment"
     *  column="Tag"
     */
	public java.lang.Integer getTag () {
		return _tag;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _tag the new ID
	 */
	public void setTag (java.lang.Integer _tag) {
		this._tag = _tag;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Lat
	 */
	public java.lang.String getLat () {
		return _lat;
	}

	/**
	 * Set the value related to the column: Lat
	 * @param _lat the Lat value
	 */
	public void setLat (java.lang.String _lat) {
		this._lat = _lat;
	}

  	/**
	 * Return the value associated with the column: Long
	 */
	public java.lang.String getLong () {
		return _long;
	}

	/**
	 * Set the value related to the column: Long
	 * @param _long the Long value
	 */
	public void setLong (java.lang.String _long) {
		this._long = _long;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof entity.base.BaseGeolocalisation)) return false;
		else {
			entity.base.BaseGeolocalisation mObj = (entity.base.BaseGeolocalisation) obj;
			if (null == this.getTag() || null == mObj.getTag()) return false;
			else return (this.getTag().equals(mObj.getTag()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getTag()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getTag().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}