#! /bin/sh -e

TOMME_XML=$1

DB_ADDRESS="127.0.0.1"

sed -i "s/USERNAME/$DB_USERNAME/g" $TOMME_XML
sed -i "s/PASSWORD/$DB_PASSWORD/g" $TOMME_XML
sed -i "s/ADDRESS/$DB_ADDRESS/g" $TOMME_XML
sed -i "s/DB_NAME/$DB_NAME/g" $TOMME_XML
